- name: Install Apache2
  ansible.builtin.apt:
    update_cache: true
    name:
      - apache2
    state: present
- name: Enable apache service
  ansible.builtin.service:
    name: apache2
    enabled: true
- name: Enable modules
  community.general.apache2_module:
    name: "{{ item.module }}"
    state: "{{ item.state }}"
  loop:
  - module: ssl
    state: present
  - module: rewrite
    state: present
  - module: proxy_http
    state: present
  notify:
    - restart apache
- name: Creating Apache Vhost
  ansible.builtin.template:
    src: explain.conf.j2
    dest: /etc/apache2/sites-available/explain.conf
    mode: '0644'
  notify:
    - syntax check
    - enable site
    - reload apache

