- name: Install Apache2
  ansible.builtin.apt:
    update_cache: true
    name:
      - apache2
    state: present
#- name: Creating Apache Vhost
#  ansible.builtin.template:
#    src: {{ apache_vhost_file }}
#    dest: {{ apache_vhost_path }}
#    notify:
#    - restart apache
- name: Enable apache service
  ansible.builtin.service:
    name: apache2
    enabled: true
