- name: Install postgresql
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql
    state: present
- name: Enable postgresql service
  ansible.builtin.service:
    name: '{{ postgresql_service }}'
    enabled: true
# Créer la base de données
# Copier le fichier template postgresql.conf vers la cible
# Copier le fichier template pg_hba.conf vers la cible
# Redémarrer le service postgresql

