- name: Install postgresql
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql
    state: present
- name: Enable postgresql service
  ansible.builtin.service:
    name: '{{ postgresql_service }}'
    enabled: true
