- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ dalibo_explain_app_path }}'
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
- name: Download explain
  ansible.builtin.get_url:
    url: '{{ dalibo_explain_release_url }}'
    dest: /var/tmp
    mode: '0755'
    checksum: '{{ dalibo_explain_checksum }}'
  notify:
    - extract archive
    - configure app
# Initialiser l'app avec les commandes pip
